before:
  hooks:
    - go mod tidy -v
    - mkdir -p data
    - cp -rf script/config.yaml data/config.yaml 
    - rm -rf data/sqlite.db
    - find . -path vendor -prune -name ".DS_Store" -print -delete
builds:
  - id: nezha
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS="-static"
      - CC=x86_64-linux-musl-gcc
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - linux
    goarch:
      - amd64
    main: .
    binary: nezha

  - id: nezha-386
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS="-static"
      - CC=i486-linux-musl-gcc
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - linux
    goarch:
      - 386
    main: .
    binary: nezha

  - id: nezha-arm64
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS="-static"
      - CC=aarch64-linux-musl-gcc
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - linux
    goarch:
      - arm64
    main: .
    binary: nezha

  - id: nezha-arm
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS="-static"
      - CC=arm-linux-musleabi-gcc
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - linux
    goarch:
      - arm
    main: .
    binary: nezha

  # dev env
  # - id: darwin-amd64
  #   env:
  #     - CGO_ENABLED=1
  #     - CC=x86_64-linux-musl-gcc
  #     - CGO_LDFLAGS="-static"
  #   ldflags:
  #     - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
  #   goos:
  #     - darwin
  #   goarch:
  #     - amd64
  #   main: .
  #   binary: nezha
universal_binaries:
  - name_template: "nezha"
    replace: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "nezha"
archives:
  - name_template: "nezha-{{ .Os }}-{{ .Arch }}"
    format: zip
    files:
      - resource
      - data

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - New translations
