title: nezha
frequency: 3
dirfilter:
- tmp
- .git
- .github
- scripts
- vendor
- logs
- .github
ext:
- go
- js
- tmpl
- ini
- html
enablerun: true
action:
  before:
  - find . -path vendor -prune -name ".DS_Store" -print -delete
  - go mod tidy && go mod vendor
  after:
  - ps -ef|grep 'nezha'| grep -v grep | grep -v git | awk '{print $2}' | xargs kill -9 
  - ./nezha web &
  - ./nezha conf -u ""
  - echo "start web"
  exit:
  - ps -ef|grep 'nezha'| grep -v grep | grep -v git | awk '{print $2}' | xargs kill -9
  - rm -rf nezha
  - echo "stop web"
  # git tag v0.15.1
  # git push --tags