name: Run Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/agent.yml"
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/test-on-pr.yml"
      - ".github/workflows/contributors.yml"
      - "README.md"
      - ".goreleaser.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20.0"
      - name: Unit test
        run: |
          go test -v ./...
      - name: Build test
        run: |
          go build
      - name: Run Gosec Security Scanner
        # gosec -exclude=G104 ./...
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest

