name: Run Tests on PR

on:
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20.0"
      - name: Unit test
        run: |
          go test -v ./...
      - name: Build test
        run: |
          go build 
      - name: Run Gosec Security Scanner
        # gosec -exclude=G104 ./...
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          